version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/tool/generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/permission_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/app_ui/gallery"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/app_ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/authentication_client/authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/authentication_client/firebase_authentication_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/authentication_client/token_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/form_inputs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/storage/storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/storage/secure_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/storage/persistent_storage"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/package_info_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/email_launcher"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/user_repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/deep_link_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_app_example/packages/analytics_repository"
    schedule:
      interval: "daily"
