name: flutter_news_example
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.16.9
dependencies:
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  clock: ^1.1.0
  collection: ^1.16.0
  deep_link_client:
    path: packages/deep_link_client
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.3
  firebase_analytics: ^10.0.3
  firebase_auth_platform_interface: ^7.0.9
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.0.3
  firebase_dynamic_links: ^5.0.3
  firebase_messaging: ^14.0.3
  flow_builder: ^0.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  form_inputs:
    path: packages/form_inputs
  google_mobile_ads: ^4.0.0
  hydrated_bloc: ^9.0.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  mockingjay: ^0.5.0
  package_info_client:
    path: packages/package_info_client
  path_provider: ^2.0.2
  permission_client:
    path: packages/permission_client
  persistent_storage:
    path: packages/storage/persistent_storage
  share_launcher:
    path: packages/share_launcher
  shared_preferences: ^2.0.15
  test: ^1.21.4
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.0.9
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^5.1.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.3
  build_verify: ^3.0.0
  build_version: ^2.0.3
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.2
  mocktail_image_network: ^1.0.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  generate: true
  uses-material-design: true
