name: ads_consent_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "flutter_news_example/packages/ads_consent_client/**"
      - ".github/workflows/ads_consent_client.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.24.2
      working_directory: flutter_news_example/packages/ads_consent_client
      coverage_excludes: "lib/src/generated/*.dart"
