name: generate_flutter_app_template

on:
  push:
    paths:
      - tool/generator/**
      - flutter_app_example/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        working-directory: tool/generator
        run: dart pub get

      - name: Generate Template
        run: dart ./tool/generator/main.dart

      - name: Stash New Template Version
        # Save the new version of the template to apply the changes later.
        run: git stash -u

      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: templates

      - name: Clean Up Current Template
        # Delete the current version of the template using git to keep
        # track of all changes afterwards.
        run: git rm -r --ignore-unmatch flutter_app_template/__brick__

      - name: Unstash New Template Version
        # Pop the new version of the template previously saved to compare it with
        # the previous deleted one to keep track of all changes, including deletions.
        run: git stash pop

      - name: Create Pull Request With Required Changes
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          branch: chore/generate-flutter-app-template
          commit-message: "chore: generate flutter_app_template"
          title: "chore: generate flutter_app_template"
          body: Please squash and merge me!
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: elianortega
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
