name: {{project_name.snakeCase()}}
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: {{flutter_version}}

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^8.1.4
  deep_link_client:
    path: packages/deep_link_client/deep_link_client
  email_launcher:
    path: packages/email_launcher
  equatable: ^2.0.3
  firebase_analytics: ^11.3.1
  firebase_auth: ^5.2.1
  firebase_auth_platform_interface: ^7.4.5
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.1
  firebase_deep_link_client:
    path: packages/deep_link_client/firebase_deep_link_client
  firebase_dynamic_links: ^6.0.6
  firebase_messaging: ^15.1.1
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  flow_builder: ^0.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  form_inputs:
    path: packages/form_inputs
  go_router: ^14.2.8
  hydrated_bloc: ^9.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockingjay: ^0.6.0
  package_info_client:
    path: packages/package_info_client
  path_provider: ^2.1.4
  persistent_storage:
    path: packages/storage/persistent_storage
  shared_preferences: ^2.2.3
  test: ^1.21.4
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.2.6
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^6.0.0
  video_player_platform_interface: ^6.0.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  build_verify: ^3.1.0
  build_version: ^2.1.1
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.2
  mocktail_image_network: ^1.0.0

dependency_overrides:
  intl: ^0.19.0
  win32: ^5.5.4

flutter:
  generate: true
  uses-material-design: true
